apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qzelc7bui-go 
  janus-idp.io/tekton: qzelc7bui-go
  backstage.io/kubernetes-id: qzelc7bui-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qzelc7bui-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml