apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: qzelc7bui-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:dd14327050b78f3f59b05e4092c5ceb74c78187d@sha256:e58d8adac7b38a4ed56f87cb76660100e05ae697b1296701d018c6ecb84a3773
          name: container-image
