apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qzelc7bui-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qzelc7bui-go 
  name: qzelc7bui-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qzelc7bui-go 
